#!/bin/bash

find . -maxdepth 1 \
    -not -path . \
    -not -path ./.pc \
    -not -path ./debian \
    -not -path ./.git \
    -not -path ./.github \
    -printf "%f usr/share/icingaweb2/modules/sso\n"
