#!/bin/sh

set -e

case "$1" in
    configure)
        # Only on install
        if [ -z "$2" ]; then
          ln -sf /usr/share/icingaweb2/modules/sso /etc/icingaweb2/enabledModules/sso
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
